notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    # Unit tests on node 10
    - language: node_js
      node_js: 14

    # Website
    # - language: node_js
    #   env:
    #     - NAME='Website - master'
    #   node_js: 8
    #   script:
    #   - scripts/publish-website.sh
